---
# tasks file for release
- name: clone for repositories
  git:
    repo: https://sureshreddyp:suresh123@github.com/sureshreddyp/{{ item }}.git
    dest: '{{ dir }}/{{ item }}'
    force: no
    version: master
    update: no
  with_items: 
    - '{{ repolist }}'
#- name: pull to remote
#  command: 'git pull origin master'
#  command: 'git pull origin {{ branname }}'
#  args:
 #  chdir: '{{ dir }}/{{ item }}'
 # with_items:
 #   - '{{ repolist }}'
 # ignore_errors: yes
- name: checkout branch
  command: 'git checkout -b {{ branname }}'
  args:
    chdir: '{{ dir }}/{{ item }}' 
  with_items:
    - '{{ repolist }}'
  ignore_errors: yes
- name: change artifactid in pom file
  include: change_pom.yml
- name: creating file in branch
  shell: "echo hello world>>file1"
  args:
    chdir: '{{ dir }}/{{ item }}'
  with_items:
    - '{{ repolist }}'
- name: modify previous file
  blockinfile:
     dest: '{{ dir }}/{{ item }}/README.md'
     marker: "<!-- {mark} ANSIBLE MANAGED BLOCK --->"
     block: |
       hello {{ var1 }}
  with_items:
    - '{{ repolist }}'
- name: add to staging area
  command: 'git add .'
  args:
    chdir: '{{ dir }}/{{ item }}'
  with_items:
    - '{{ repolist }}'
- name: commit file
  command: 'git commit -m "this is file"'
  args:
    chdir: '{{ dir }}/{{ item }}'
  with_items:
    - '{{ repolist }}'
# this is pull remote repo code it's working
#- name: pull to remote
#  command: 'git pull origin {{ branname }}'
#  args: 
#   chdir: '{{ dir }}/{{ item }}'
#  with_items:
#    - '{{ repolist }}'
#  notify: add
  ignore_errors: yes
# pull end
- name: push to remote
  command: 'git push -u origin {{ branname }}'
  args:
    chdir: '{{ dir }}/{{ item }}'
  with_items:
    - '{{ repolist }}'
- name: clean dir
  shell: rm -Rf /home/ec2-user/autorel/*



